### ISSUE TITLE
Error when verifying arduino code

### ISSUE THREAD

**Issue by zachikibuta** [jasoncoon/BlinkyTileFastLED#1]
Have the Dmx Simple, FastLED and Adafruit_LSM303 libraries installed and I can see them from the Sketch menu of Arduino 1.0.6 but when I verify the code I got this error. 

Arduino: 1.0.6 (Mac OS X), Board: "Arduino Uno"
Arduino.app/Contents/Resources/Java/hardware/arduino/cores/arduino Arduino.app/Contents/Resources/Java/hardware/arduino/variants/standard -
Arduino/libraries/DmxSimple -I/Users/macanthropus/Documents/Arduino/libraries/FastLED-3.1.0 -Arduino.app/Contents/Resources/Java/libraries/Wire -
Arduino/libraries/Adafruit_LSM303-master /var/folders/s3/lqlyl00127dc8wtfdk_ygtl00000gn/T/build7414988327060524094.tmp/sketch_jan08a.cpp -o /var/folders/s3/lqlyl00127dc8wtfdk_ygtl00000gn/T/build7414988327060524094.tmp/sketch_jan08a.cpp.o 
In file included from sketch_jan08a.ino:2:
Arduino/libraries/FastLED-3.1.0/FastLED.h:12:2: warning: #warning FastLED version 3.001.000 (Not really a warning, just telling you here.)
sketch_jan08a:427: error: 'BLEND' was not declared in this scope
sketch_jan08a.ino: In function 'void ChangePalettePeriodically()':
sketch_jan08a:460: error: 'BLEND' was not declared in this scope
sketch_jan08a:464: error: 'BLEND' was not declared in this scope
sketch_jan08a:472: error: 'BLEND' was not declared in this scope
sketch_jan08a:476: error: 'BLEND' was not declared in this scope
sketch_jan08a:480: error: 'BLEND' was not declared in this scope
sketch_jan08a:488: error: 'BLEND' was not declared in this scope
sketch_jan08a:492: error: 'BLEND' was not declared in this scope
sketch_jan08a:496: error: 'BLEND' was not declared in this scope
sketch_jan08a:504: error: 'BLEND' was not declared in this scope

**Comment by jasoncoon** [comment]
Try changing BLEND to LINEARBLEND.  It got renamed a while back: https://github.com/FastLED/FastLED/issues/131#issuecomment-101862204

If that works, feel free to submit a pull request.

**Comment by zachikibuta** [comment]
Thanks. Now I got this message

/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:11:20: error: wiring.h: No such file or directory
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp: In function 'void dmxBegin()':
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:57: error: 'digitalPinToPort' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:57: error: 'portOutputRegister' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:58: error: 'digitalPinToBitMask' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:61: error: 'OUTPUT' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:61: error: 'pinMode' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp: In function 'void dmxWrite(int, uint8_t)':
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:183: error: 'max' was not declared in this scope
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp: In function 'void dmxMaxChannel(int)':
/Users/macanthropus/Documents/Arduino/libraries/DmxSimple/DmxSimple.cpp:194: error: 'min' was not declared in this scope

**Comment by jasoncoon** [comment]
Ah, try this version of the DmxSimple library instead: https://github.com/PaulStoffregen/DmxSimple

**Comment by zachikibuta** [comment]
It compiled! :)

**Comment by jasoncoon** [comment]
Cool!  I'll get the readme updated to point to the proper library.
